### PR TITLE
Boto 3 / Python 3 support

### PR DESCRIPTION
**Pull request by offbyone**
* Depend on boto3 instead of boto 2.x
* Add trove classifiers for Python 3

### CODE REVIEW

**Comment by rdegges** [comment]
Can you send this PR to the `develop` branch instead? Ty!

**Comment by offbyone** [comment]
Will do. I also have to update the tests.

**Comment by rdegges** [comment]
Thanks =) I had also already started on some Python3 stuff in develop, some some of the travis.yml stuff is already updated / etc. Any help is totally welcome! <3

**Comment by rdegges** [comment]
Going to close this one out for now.

**Pull request closed without merging**
