### PR TITLE
Add support for EC2 instance profile credentials

### PR DESCRIPTION
**Pull request by memory**
Or rather, get out of boto's way in this situation: having no credentials specified in the running environment is occasionally the correct thing to do.

### CODE REVIEW

**Comment by dcosson** [comment]
+1

I wouldn't even say "occasionally" and wouldn't log a warning. (I just find it way simpler to use iam instance profiles rather than passing credentials on EC2).

**Comment by boivie** [comment]
@rdegges: Could you have a look at this one? I agree with @dcosson that there shouldn't be a warning log since this is perfectly fine when using IAM roles. I am maintaining my own fork with a similar commit added, but I'd rather not.

**Comment by rdegges** [comment]
Sorry for being so lazy and slow on this ya'll. My work life has been sorta crazy. I'm going to remove the logging, but keep the rest of the stuff so that Boto can do it's thing.

My initial intent was to avoid letting boto do it's thing as I wanted to use prefixed configuration names to match the package name. In all honesty though, it's just too much work to replicate the boto stuff for such a small library =)

**Comment by rdegges** [comment]
New release just cut with this stuff included. Hope it helps!

**Comment by memory** [comment]
Awesome, thanks!

On Sun, Mar 29, 2015 at 4:37 AM, Randall Degges <notifications@github.com>
wrote:

> New release just cut with this stuff included. Hope it helps!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rdegges/flask-dynamo/pull/8#issuecomment-87371556>.
>



-- 
Everyone knows history moves in circles;
the surprise is how big the circles are.
  (--Greil Marcus)

**Comment by boivie** [comment]
@rdegges Thanks a lot!

**Pull request merged**
